# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestRer():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_rer(self):
        self.driver.get("https://gpn-sm.relex.ru/")
        self.driver.set_window_size(1936, 1056)
        self.driver.find_element(By.LINK_TEXT, "Проекты").click()
        self.driver.find_element(By.CSS_SELECTOR, ".k-state-active").click()
        self.driver.find_element(By.LINK_TEXT, "Проект OTS Express").click()
        self.driver.find_element(By.ID, "submitButton").click()
        self.driver.execute_script("window.scrollTo(0,0)")
        self.driver.find_element(By.CSS_SELECTOR, ".k-state-hover > .k-select > .k-icon").click()
        self.driver.find_element(By.CSS_SELECTOR, ".k-state-focused > .k-select > .k-icon").click()
        element = self.driver.find_element(By.CSS_SELECTOR, "#IdBranchManager-list > .k-list-scroller")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).click_and_hold().perform()
        element = self.driver.find_element(By.CSS_SELECTOR, "#IdBranchManager-list > .k-list-scroller")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        element = self.driver.find_element(By.CSS_SELECTOR, "#IdBranchManager-list > .k-list-scroller")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).release().perform()
        self.driver.find_element(By.CSS_SELECTOR, ".k-state-hover").click()
        self.driver.find_element(By.CSS_SELECTOR, ".k-state-hover > .k-select").click()
        element = self.driver.find_element(By.CSS_SELECTOR, "#IdTerritoryManager-list > .k-list-scroller")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).click_and_hold().perform()
        element = self.driver.find_element(By.CSS_SELECTOR, "#IdTerritoryManager-list > .k-list-scroller")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        element = self.driver.find_element(By.CSS_SELECTOR, "#IdTerritoryManager-list > .k-list-scroller")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).release().perform()
        self.driver.find_element(By.CSS_SELECTOR, ".k-state-hover").click()
        self.driver.find_element(By.CSS_SELECTOR, ".k-state-hover > .k-select").click()
        element = self.driver.find_element(By.CSS_SELECTOR, "#IdLaboratory-list > .k-list-scroller")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).click_and_hold().perform()
        element = self.driver.find_element(By.CSS_SELECTOR, "#IdLaboratory-list > .k-list-scroller")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        element = self.driver.find_element(By.CSS_SELECTOR, "#IdLaboratory-list > .k-list-scroller")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).release().perform()
        self.driver.find_element(By.CSS_SELECTOR, ".k-state-hover").click()
        self.driver.find_element(By.ID, "Claim_BatchNumber").click()
        self.driver.find_element(By.ID, "Claim_BatchNumber").send_keys("123")
        self.driver.find_element(By.ID, "Claim_BatchDate").click()
        self.driver.find_element(By.CSS_SELECTOR, ".k-state-hover > .k-select").click()
        self.driver.find_element(By.LINK_TEXT, "5").click()
        self.driver.find_element(By.ID, "Claim_Purpose").click()
        self.driver.find_element(By.ID, "Claim_Purpose").send_keys("test")
        self.driver.find_element(By.CSS_SELECTOR, ".k-d-flex-row:nth-child(7) .k-d-flex-row:nth-child(2)").click()
        self.driver.find_element(By.ID, "projectTabStrip-1").click()
        self.driver.find_element(By.ID, "Claim_ProductSaleVolume").send_keys("4")
        self.driver.find_element(By.CSS_SELECTOR, ".k-d-flex-row:nth-child(6) > .k-form-field").click()
        self.driver.find_element(By.ID, "Claim_FuelSupplier").click()
        self.driver.find_element(By.ID, "Claim_FuelSupplier").send_keys("rrr")
        self.driver.find_element(By.ID, "Claim_ConcurrentOilName").click()
        self.driver.find_element(By.ID, "Claim_ConcurrentOilName").send_keys("eee")
        self.driver.find_element(By.ID, "saveButton").click()

