# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By

class TestTest1():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def wait_for_window(self, timeout=2):
        time.sleep(round(timeout / 1000))
        wh_now = self.driver.window_handles
        wh_then = self.vars["window_handles"]
        if len(wh_now) > len(wh_then):
            return set(wh_now).difference(set(wh_then)).pop()

    def test_test1(self):
        self.open_home_page()
        self.expand_browser_window()
        self.open_groups_page()
        # переход по вкладке на другую страницу
        self.driver.find_element(By.LINK_TEXT, "Как можно и нельзя автоматизировать").click()
        self.vars["win3452"] = self.wait_for_window(2000)
        self.driver.switch_to.window(self.vars["win3452"])

    def open_groups_page(self):
        # переход по вкладкам
        self.driver.find_element(By.LINK_TEXT, "Гуглить").click()
        self.driver.find_element(By.CSS_SELECTOR, "#menu-item-163 > a").click()
        self.driver.find_element(By.CSS_SELECTOR, "#menu-item-12 > a").click()
        self.driver.find_element(By.LINK_TEXT, "Автоматизировать").click()
        self.vars["window_handles"] = self.driver.window_handles

    def expand_browser_window(self):
        # Expand browser window
        self.driver.set_window_size(1936, 1056)

    def open_home_page(self):
        # open home page
        self.driver.get("http://testbase.ru/")

